### ISSUE TITLE
U retarded?

### ISSUE THREAD

**Issue by XnorsMUM** [XnorDre/Hazzze---Cracked#1]
Hello my son! 
Why are u posting public available repositorys from github as cacked cheat?
Eventhough it isnt oneXD 
Maybe tried before posting Launching the "cheat"?
But if u did u may have realized nothing happens cuzz that dll is just for storing some functionsXDDDDDDD
Pls just go to ur room and shame urself for being so dumb

**Comment by XnorDre** [comment]
Soooo maad! : ))))
